### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by dchmelik** [andrewtweber/umoria-color#7]
This happens on Slackware64-current and KDE Neon 5.22 (like Kubuntu 20.04) GNU/Linuxes.
```
make
...
[ 28%] Building CXX object CMakeFiles/umoria.dir/src/dungeon.cpp.o
/home/d/umoria-color-5.8.2/src/dungeon.cpp: In function ‘int caveGetTileColor(const Coord_t&)’:
/home/d/umoria-color-5.8.2/src/dungeon.cpp:253:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
  253 |                 if ((game.treasure.list[tile.treasure_id].sub_category_id & (ITEM_SINGLE_STACK_MIN - 1)) < MAX_MUSHROOMS) {
      |                 ^~
/home/d/umoria-color-5.8.2/src/dungeon.cpp:256:13: note: here
  256 |             default:
      |             ^~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/umoria.dir/build.make:272: CMakeFiles/umoria.dir/src/dungeon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/umoria.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by lea2501** [comment]
Facing the same error here, in a devuan linux:

```
/home/lea/src/umoria-color/src/dungeon.cpp: In function ‘int caveGetTileColor(const Coord_t&)’:
/home/lea/src/umoria-color/src/dungeon.cpp:253:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
  253 |                 if ((game.treasure.list[tile.treasure_id].sub_category_id & (ITEM_SINGLE_STACK_MIN - 1)) < MAX_MUSHROOMS) {
      |                 ^~
/home/lea/src/umoria-color/src/dungeon.cpp:256:13: note: here
  256 |             default:
      |             ^~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/umoria.dir/build.make:264: CMakeFiles/umoria.dir/src/dungeon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/umoria.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

my gcc version is 10:
`$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110`

Kernel is 5.10.0:
`$ uname -a
Linux devuan 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux`

**Comment by andrewtweber** [comment]
wow sorry, I wasn't watching this repo and didn't realize there had been issues opened. Has either of you been able to figure it out? @dchmelik @lea2501

**Comment by andrewtweber** [comment]
I think I just needed to add a `// fall through` comment so that the compiler knows I am intentionally not breaking from that switch statement.

Committed to master: https://github.com/andrewtweber/umoria-color/commit/a96b8bbd81369cd1341d8be04f8750b492f1d7e5

Please fetch the code and try again and let me know if it works. Sorry for the delay

**Comment by dchmelik** [comment]
> wow sorry, I wasn't watching this repo and didn't realize there had been issues opened. Has either of you been able to figure it out?

Comment out CMakeLists.txt: set(cxx_warnings "${cxx_warnings} -Werror"). If you don't more will happen (see below)... I discovered this in recent days but there are bigger issues: the unofficial umoria fork you added colour back to was (I thought) not altering Moria 5.6 (algorithms/gameplay) except for updating to C++. The 5.7 fork has major differences with some aspects non-working/removed.

```
[ 98%] Building CXX object CMakeFiles/umoria.dir/src/wizard.cpp.o
> /home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/game_save.cpp: In function ‘bool loadGame(bool&)’:
> /home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/game_save.cpp:810:29: error: array subscript 66 is above array bounds of ‘Tile_t [66][198]’ [-Werror=array-bounds]
>   810 |                 if (tile >= &dg.floor[MAX_HEIGHT][0]) {
>       |                             ^~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/headers.h:59,
>                  from /home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/game_save.cpp:8:
> /home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/dungeon.h:55:12: note: while referencing ‘Dungeon_t::floor’
>    55 |     Tile_t floor[MAX_HEIGHT][MAX_WIDTH];
>       |            ^~~~~
> cc1plus: all warnings being treated as errors
> make[2]: *** [CMakeFiles/umoria.dir/build.make:370: CMakeFiles/umoria.dir/src/game_save.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/umoria.dir/all] Error 2

make: *** [Makefile:91: all] Error 2
```
Comment out CMakeLists.txt: set(cxx_warnings "${cxx_warnings} -Werror").

**Comment by dchmelik** [comment]
> wow sorry, I wasn't watching this repo and didn't realize there had been issues opened. Has either of you been able to figure it out?

Comment out CMakeLists.txt: set(cxx_warnings "${cxx_warnings} -Werror"). I discovered this in recent days but there are bigger issues: the unofficial umoria fork you added colour back to was (I thought) not altering Moria 5.6 (algorithms/gameplay) except for updating to C++. The gameplay isn't even the same with some non-working/removed.

**Comment by andrewtweber** [comment]
@dchmelik the other commenter who had the same issue on Debian has it compiling successfully now that I’ve updated my color fork with the upstream.

If you’re able to try it again let me know if it’s working on your system too

**Comment by dchmelik** [comment]
I was able to compile also, though I'm having some other problems with the game which may depend what type of terminal I'm running it in.
